export type Agency = {
  id: string;
  name: string;
  category: string;
  email: string | null;
  phone: string | null;
  website: string | null;
  location: string | null;
  state: string;
  notes: string | null;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  abn: string | null;
  address: string | null;
  city: string | null;
  confidenceScore: number;
  contactType: string | null;
  eligible88Days: boolean;
  eligible88Days462: boolean;
  emailCareers: string | null;
  googleRating: number | null;
  googleReviewsCount: number | null;
  isActivelyRecruiting: boolean;
  phoneSecondary: string | null;
  postcode: string | null;
  salaryMin: number | null;
  salaryMax: number | null;
  salaryUnit: string | null;
  isSpecialist: boolean;
};
